### PR TITLE
Fix mounting aufs when there's several layers and use random path for mount

### LINKED ISSUE #9: Docker::imageRootDirMounted fails when there's too many layers
Mount options are clipped to page size so the passed mount options are wrong, causing an "Invalid arguments" error.
Docker solves this by mounting passing up to 4096 bytes in options (but clipping at an appropriate point) and then appending layers to the mount, as seen here https://github.com/docker/docker/blob/master/daemon/graphdriver/aufs/aufs.go#L595 - we need to adapt this to our JS code.

### PR DESCRIPTION
**Pull request by pcarranzav**
Fixes #9 

mount limits the mount options to page size (usually 4096 bytes), so we do what docker does
to mount when layers don't fit in that: we mount with as much as we can fit and then
remount appending each remaining layer. We stick to 4096 instead of actually finding the page size
cause it's assured to work (4096 is the minimum in the arches we support), reduces complexity and
shouldn't generate much overhead (we don't care about a few extra remounts).

Based on https://github.com/docker/docker/blob/b937aa8e6968d805527d163e6f477d496ceb88d7/daemon/graphdriver/aufs/aufs.go#L595

We also introduce 8 random characters to the temporary path we use for the aufs mount, so that
several calls to this function can work independently.

Signed-off-by: Pablo Carranza Velez <pablo@resin.io>

### CODE REVIEW

File: lib/docker-toolbelt.coffee [hunk 1]
```diff
@@ -102,6 +102,42 @@ Docker::imageRootDir = (image) ->
...
+	fs.mkdirAsync(target)
+	.catch EEXIST, ignore
+	.then ->
+		appendFromIndex = null
+		options = 'noxino,ro,br='
+		remainingBytes = 4096 - options.length
+		for i in [0...layerDiffPaths.length]
+			nextBranch = layerDiffPaths[i] + '=ro+wh'
+			nextBranch = ':' + nextBranch if i > 0
+			if remainingBytes - nextBranch.length < 0
```
Comment (Page-) [inline lib/docker-toolbelt.coffee]: `remainingBytes` is never changed after the first check, which seems like a bug?

File: lib/docker-toolbelt.coffee [hunk 2]
```diff
@@ -102,6 +102,42 @@ Docker::imageRootDir = (image) ->
...
+				appendFromIndex = i
+				break
+			options += nextBranch
+		execAsync("mount -t aufs -o '#{options}' none #{target}")
+		.then ->
+			if appendFromIndex
+				Promise.mapSeries [appendFromIndex...layerDiffPaths.length], (i) ->
+					execAsync("mount -t aufs -o 'remount,append:#{layerDiffPaths[i]}=ro+wh' none #{target}")
```
Comment (Page-) [inline lib/docker-toolbelt.coffee]: Can you only append one set at a time? Or does it also have the 4096 limit we can go up to by combining layers?

File: lib/docker-toolbelt.coffee [hunk 3]
```diff
@@ -102,6 +102,42 @@ Docker::imageRootDir = (image) ->
...
+aufsMountWithDisposer = (target, layerDiffPaths) ->
+	# We try to create the target directory.
+	# If it exists, it's *probably* from a previous run of this same function,
+	# and the mount will fail if the directory is not empty or something's already mounted there.
+	fs.mkdirAsync(target)
+	.catch EEXIST, ignore
+	.then ->
+		appendFromIndex = null
+		options = 'noxino,ro,br='
+		remainingBytes = 4096 - options.length
```
Comment (Page-) [inline lib/docker-toolbelt.coffee]: It'd be nice to give the 4096 a named value for self-documenting

File: lib/docker-toolbelt.coffee (hunk 2 above)
Comment (pcarranzav) [inline lib/docker-toolbelt.coffee]: Nope, `append` takes a single branch ([source](http://aufs.sourceforge.net/aufs.html))

File: lib/docker-toolbelt.coffee (hunk 1 above)
Comment (pcarranzav) [inline lib/docker-toolbelt.coffee]: Oh, yes, good catch (should've marked this as WIP as it's just my first go at coding it, I still have to test it)

File: lib/docker-toolbelt.coffee (hunk 3 above)
Comment (pcarranzav) [inline lib/docker-toolbelt.coffee]: Done

File: lib/docker-toolbelt.coffee [hunk 4]
```diff
@@ -102,6 +102,44 @@ Docker::imageRootDir = (image) ->
...
+	# We try to create the target directory.
+	# If it exists, it's *probably* from a previous run of this same function,
+	# and the mount will fail if the directory is not empty or something's already mounted there.
+	fs.mkdirAsync(target)
+	.catch code: EEXIST, ignore
+	.then ->
+		appendFromIndex = null
+		options = 'noxino,ro,br='
+		remainingBytes = MIN_PAGE_SIZE - options.length
+		for i in [0...layerDiffPaths.length]
```
Comment (Page-) [inline lib/docker-toolbelt.coffee]: I think this entire loop could be replaced by something like
```coffee
[initialLayerPaths, appendLayerPaths] = _(layerDiffPaths)
.map (path) ->
	return "#{path}=ro+wh"
.partition (path) ->
	remainingBytes -= path.length + 1
	# >= -1 because if this is the last entry we won't actually add the comma
	return remainingBytes >= -1
.value()
options += initialLayerPaths.join(':')
...
Promise.mapSeries [appendLayerPaths], (path) ->
	execAsync("mount -t aufs -o 'remount,append:#{path}' none #{target}")
```
(I'm not 100% on this precise version, but I definitely like the `.map (path) -> "#{path}=ro+wh"` to format them all in one pass/one place)

**Comment by pcarranzav** [comment]
@Page- @petrosagg @lekkas ping for review, tested `imageRootDirMounted` on my laptop and it works well (tested with an image with more than 60 layers and it works well)

File: lib/docker-toolbelt.coffee [hunk 5]
```diff
@@ -102,6 +102,45 @@ Docker::imageRootDir = (image) ->
...
+	# We try to create the target directory.
+	# If it exists, it's *probably* from a previous run of this same function,
+	# and the mount will fail if the directory is not empty or something's already mounted there.
+	fs.mkdirAsync(target)
+	.catch code: EEXIST, ignore
+	.then ->
+		appendFromIndex = null
+		options = 'noxino,ro,br='
+		remainingBytes = MIN_PAGE_SIZE - options.length
+		for path, i in layerDiffPaths
```
Comment (Page-) [inline lib/docker-toolbelt.coffee]: A pure cs version of the previous lodash:
```coffee
layerDiffPaths = layerDiffPaths.map (path) ->
	return "#{path}=ro+wh"
appendFromIndex = layerDiffPaths.findIndex (path) ->
	remainingBytes -= path.length + 1
	# >= -1 because if this is the last entry we won't actually add the comma
	return remainingBytes >= -1
initialLayerPaths = layerDiffPaths[...appendFromIndex]
appendLayerPaths = layerDiffPaths[appendFromIndex...]
options += initialLayerPaths.join(':')
...
Promise.mapSeries [appendLayerPaths], (path) ->
	execAsync("mount -t aufs -o 'remount,append:#{path}' none #{target}")
```

Comment (pcarranzav) [inline lib/docker-toolbelt.coffee]: Good idea.  Done (had to tweak a few things for the conversion from `.partition` to using `.findIndex` to work)

Comment (Page-) [inline lib/docker-toolbelt.coffee]: duh yeah, I meant to do that but forgot, sorry

File: lib/docker-toolbelt.coffee [hunk 6]
```diff
@@ -102,6 +102,44 @@ Docker::imageRootDir = (image) ->
...
+	fs.mkdirAsync(target)
+	.catch code: EEXIST, ignore
+	.then ->
+		options = 'noxino,ro,br='
+		remainingBytes = MIN_PAGE_SIZE - options.length
+		layerDiffPaths = layerDiffPaths.map (path) ->
+			return "#{path}=ro+wh"
+		appendFromIndex = layerDiffPaths.findIndex (path) ->
+			remainingBytes -= path.length + 1
+			# >= -1 because if this is the last entry we won't actually add the comma
```
Comment (Page-) [inline lib/docker-toolbelt.coffee]: You should update the comment here btw
